version: '1.0'
name: pipeline-20230128
displayName: pipeline-20230128
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-35c8871b
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: 打包
        nodeVersion: 14.16.0
        commands:
          - yum -y install ncftp
          - '#ncftpput -u jiacai -p jiacai -m -R 77.74.54.201 /htdocs/docs/1.0.0 ./jc/*'
          - ncftpput -u hyu7385950001 -p Uwant123 -m -R hyu7385950001.my3w.com /htdocs/docs ./test/*
          - echo "ncftp upload successfully"
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
