version: '1.0'
name: pipeline-20230128
displayName: pipeline-20230128
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-35c8871b
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: 打包
        nodeVersion: 14.16.0
        commands:
          - yum install ftp -y
          - wget ftp://ftp.ncftp.com/ncftp/ncftp-3.2.6-src.zip
          - ftp -n -i hyu7385950001.my3w.com <<EOF
          - user hyu7385950001 Uwant123
          - ls
          - cd /htdocs
          - put ncftp-3.2.6-src.zip
          - bye
          - EOF
          - echo "PUT FTP successfully."
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
