version: '1.0'
name: pipeline-20230128
displayName: pipeline-20230128
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-35c8871b
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: 打包
        nodeVersion: 14.16.0
        commands:
          - uname -a
          - yum -y install ftp
          - 'ftp 77.74.54.201 '
          - user jiacai jiacai
          - ls
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
